openapi: 3.2.0
info:
  description: '# Overview


    This guide documents the InsightVM Application Programming Interface (API) Version 3.'
  version: '3'
  title: InsightVM Remediation API
  contact:
    name: Rapid7
    email: support@rapid7.com
servers:
- url: https://localhost:3780/
tags:
- name: Remediation
  description: Resources for determining the details required to remediate vulnerabilities.
paths:
  /api/3/assets/{id}/vulnerabilities/{vulnerabilityId}/solution:
    get:
      tags:
      - Remediation
      summary: Asset Vulnerability Solution
      description: Returns the highest-superceding rollup solutions for a vulnerability on an asset. The solution(s) selected will be the most recent and cost-effective means by which the vulnerability can be remediated.
      operationId: getAssetVulnerabilitySolutions
      parameters:
      - name: id
        in: path
        description: The identifier of the asset.
        required: true
        schema:
          type: integer
          format: int64
      - name: vulnerabilityId
        in: path
        description: The identifier of the vulnerability.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Resources_MatchedSolution'
        '401':
          description: Unauthorized
          headers: {}
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
        '404':
          description: Not Found
          headers: {}
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        '500':
          description: Internal Server Error
          headers: {}
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/InternalServerError'
        '503':
          description: Service Unavailable
          headers: {}
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ServiceUnavailableError'
      security: []
components:
  schemas:
    InternalServerError:
      type: object
      required:
      - status
      properties:
        links:
          type: array
          description: Hypermedia links to corresponding or related resources.
          items:
            $ref: '#/components/schemas/Link'
        message:
          type: string
          example: An error has occurred.
          description: The messages indicating the cause or reason for failure.
        status:
          type: string
          example: '500'
          description: The HTTP status code for the error (same as in the HTTP response).
          enum:
          - '500'
      description: ''
    AdditionalInformation:
      type: object
      properties:
        html:
          type: string
          example: ''
          description: Hypertext Markup Language (HTML) representation of the content.
        text:
          type: string
          example: ''
          description: Textual representation of the content.
      description: ''
    MatchedSolution:
      type: object
      properties:
        additionalInformation:
          example: ''
          description: Additional information or resources that can assist in applying the remediation.
          $ref: '#/components/schemas/AdditionalInformation'
        appliesTo:
          type: string
          example: libexpat1 on Ubuntu Linux
          description: The systems or software the solution applies to.
        confidence:
          type: string
          example: ''
          description: The confidence of the matching process for the solution.
          enum:
          - exact
          - partial
          - none
        estimate:
          type: string
          example: PT10M
          description: 'The estimated duration to apply the solution, in ISO 8601 format. For example: `"PT5M"`.'
        id:
          type: string
          example: ubuntu-upgrade-libexpat1
          description: The identifier of the solution.
        links:
          type: array
          description: Hypermedia links to corresponding or related resources.
          readOnly: true
          items:
            $ref: '#/components/schemas/Link'
        matches:
          type: array
          description: The raw matches that were performed in order to select the best solution(s).
          items:
            $ref: '#/components/schemas/SolutionMatch'
        steps:
          example: ''
          description: The steps required to remediate the vulnerability.
          $ref: '#/components/schemas/Steps'
        summary:
          example: ''
          description: The summary of the solution.
          $ref: '#/components/schemas/Summary'
        type:
          type: string
          example: configuration
          description: 'The type of the solution. One of: `"Configuration"`, `"Rollup patch"`, `"Patch"`'
          enum:
          - configuration
          - rollup-patch
          - patch
          - unknown
      description: ''
    Summary:
      type: object
      properties:
        html:
          type: string
          example: Upgrade libexpat1
          description: Textual representation of the content.
        text:
          type: string
          example: Upgrade libexpat1
          description: Textual representation of the content.
      description: ''
    Link:
      type: object
      properties:
        href:
          type: string
          example: https://hostname:3780/api/3/...
          description: 'A hypertext reference, which is either a URI (see <a target="_blank" rel="noopener noreferrer" href="https://tools.ietf.org/html/rfc3986">RFC 3986</a>) or URI template (see <a target="_blank" rel="noopener noreferrer" href="https://tools.ietf.org/html/rfc6570">RFC 6570</a>). '
        rel:
          type: string
          example: self
          description: The link relation type. This value is one from the <a target="_blank" rel="noopener noreferrer" href="https://tools.ietf.org/html/rfc5988#section-6.2">Link Relation Type Registry</a> or is the type of resource being linked to.
      description: ''
    Fingerprint:
      type: object
      properties:
        description:
          type: string
          example: Ubuntu libexpat1 2.1.0-4ubuntu1.2
          description: The description of the matched fingerprint.
        family:
          type: string
          example: ''
          description: The family of the matched fingerprint.
        product:
          type: string
          example: libexpat1
          description: The product of the matched fingerprint.
        vendor:
          type: string
          example: Ubuntu
          description: The description of the matched fingerprint.
        version:
          type: string
          example: 2.1.0-4ubuntu1.2
          description: The version of the matched fingerprint.
      description: ''
    SolutionMatch:
      type: object
      properties:
        check:
          type: string
          example: ''
          description: The identifier of the vulnerability check used to match the solution, if type is `check`.
        confidence:
          type: string
          example: ''
          description: The confidence of the matching process for the solution.
          enum:
          - exact
          - partial
          - none
        fingerprint:
          example: ''
          description: The fingerprint used to perform solution matching, if type is `operating-system`, `service`, or `software`.
          $ref: '#/components/schemas/Fingerprint'
        links:
          type: array
          description: Hypermedia links to corresponding or related resources.
          readOnly: true
          items:
            $ref: '#/components/schemas/Link'
        solution:
          type: string
          example: ubuntu-upgrade-libexpat1
          description: The identifier of the matched solution.
        type:
          type: string
          example: software
          description: The means by which a solution was matched.
          enum:
          - none
          - check
          - operating-system
          - service
          - software
      description: ''
    Steps:
      type: object
      properties:
        html:
          type: string
          example: "<p>\n    Use `apt-get upgrade` to upgrade libexpat1 to the latest version.\n  </p>"
          description: Textual representation of the content.
        text:
          type: string
          example: Use `apt-get upgrade` to upgrade libexpat1 to the latest version.
          description: Textual representation of the content.
      description: ''
    NotFoundError:
      type: object
      required:
      - status
      properties:
        links:
          type: array
          description: Hypermedia links to corresponding or related resources.
          items:
            $ref: '#/components/schemas/Link'
        message:
          type: string
          example: An error has occurred.
          description: The messages indicating the cause or reason for failure.
        status:
          type: string
          example: '404'
          description: The HTTP status code for the error (same as in the HTTP response).
          enum:
          - '404'
      description: ''
    UnauthorizedError:
      type: object
      required:
      - status
      properties:
        links:
          type: array
          description: Hypermedia links to corresponding or related resources.
          items:
            $ref: '#/components/schemas/Link'
        message:
          type: string
          example: An error has occurred.
          description: The messages indicating the cause or reason for failure.
        status:
          type: string
          example: '401'
          description: The HTTP status code for the error (same as in the HTTP response).
          enum:
          - '401'
      description: ''
    Resources_MatchedSolution:
      type: object
      properties:
        links:
          type: array
          description: Hypermedia links to corresponding or related resources.
          items:
            $ref: '#/components/schemas/Link'
        resources:
          type: array
          description: The resources returned.
          items:
            $ref: '#/components/schemas/MatchedSolution'
      description: ''
    ServiceUnavailableError:
      type: object
      required:
      - status
      properties:
        links:
          type: array
          description: Hypermedia links to corresponding or related resources.
          items:
            $ref: '#/components/schemas/Link'
        message:
          type: string
          example: An error has occurred.
          description: The messages indicating the cause or reason for failure.
        status:
          type: string
          example: '503'
          description: The HTTP status code for the error (same as in the HTTP response).
          enum:
          - '503'
      description: ''
  securitySchemes:
    Basic:
      type: http
      scheme: basic
