openapi: 3.2.0
info:
  description: '# Overview


    This guide documents the InsightVM Application Programming Interface (API) Version 3.'
  version: '3'
  title: InsightVM Root API
  contact:
    name: Rapid7
    email: support@rapid7.com
servers:
- url: https://localhost:3780/
tags:
- name: Root
  description: Provides access to primary entry point for discovering the available resources in this API.
paths:
  /api/3:
    get:
      tags:
      - Root
      summary: Resources
      description: Returns a listing of the resources (endpoints) that are available to be invoked in this API.
      operationId: resources
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Links'
        '401':
          description: Unauthorized
          headers: {}
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
        '404':
          description: Not Found
          headers: {}
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/NotFoundError'
        '500':
          description: Internal Server Error
          headers: {}
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/InternalServerError'
        '503':
          description: Service Unavailable
          headers: {}
          content:
            application/json;charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ServiceUnavailableError'
      security: []
components:
  schemas:
    InternalServerError:
      type: object
      required:
      - status
      properties:
        links:
          type: array
          description: Hypermedia links to corresponding or related resources.
          items:
            $ref: '#/components/schemas/Link'
        message:
          type: string
          example: An error has occurred.
          description: The messages indicating the cause or reason for failure.
        status:
          type: string
          example: '500'
          description: The HTTP status code for the error (same as in the HTTP response).
          enum:
          - '500'
      description: ''
    Link:
      type: object
      properties:
        href:
          type: string
          example: https://hostname:3780/api/3/...
          description: 'A hypertext reference, which is either a URI (see <a target="_blank" rel="noopener noreferrer" href="https://tools.ietf.org/html/rfc3986">RFC 3986</a>) or URI template (see <a target="_blank" rel="noopener noreferrer" href="https://tools.ietf.org/html/rfc6570">RFC 6570</a>). '
        rel:
          type: string
          example: self
          description: The link relation type. This value is one from the <a target="_blank" rel="noopener noreferrer" href="https://tools.ietf.org/html/rfc5988#section-6.2">Link Relation Type Registry</a> or is the type of resource being linked to.
      description: ''
    UnauthorizedError:
      type: object
      required:
      - status
      properties:
        links:
          type: array
          description: Hypermedia links to corresponding or related resources.
          items:
            $ref: '#/components/schemas/Link'
        message:
          type: string
          example: An error has occurred.
          description: The messages indicating the cause or reason for failure.
        status:
          type: string
          example: '401'
          description: The HTTP status code for the error (same as in the HTTP response).
          enum:
          - '401'
      description: ''
    NotFoundError:
      type: object
      required:
      - status
      properties:
        links:
          type: array
          description: Hypermedia links to corresponding or related resources.
          items:
            $ref: '#/components/schemas/Link'
        message:
          type: string
          example: An error has occurred.
          description: The messages indicating the cause or reason for failure.
        status:
          type: string
          example: '404'
          description: The HTTP status code for the error (same as in the HTTP response).
          enum:
          - '404'
      description: ''
    Links:
      type: object
      properties:
        links:
          type: array
          description: Hypermedia links to corresponding or related resources.
          items:
            $ref: '#/components/schemas/Link'
      description: ''
    ServiceUnavailableError:
      type: object
      required:
      - status
      properties:
        links:
          type: array
          description: Hypermedia links to corresponding or related resources.
          items:
            $ref: '#/components/schemas/Link'
        message:
          type: string
          example: An error has occurred.
          description: The messages indicating the cause or reason for failure.
        status:
          type: string
          example: '503'
          description: The HTTP status code for the error (same as in the HTTP response).
          enum:
          - '503'
      description: ''
  securitySchemes:
    Basic:
      type: http
      scheme: basic
