openapi: 3.2.0
info:
  title: InsightIDR Users API
  version: v1
  description: 'Introduction


    Welcome to the reference documentation for the InsightIDR public APIs.


    Here are a few resources to help you learn how to start using our APIs:


    Learn about basic concepts and capabilities


    Get an Insight platform API key to set up authentication


    See available Insight product APIs


    Learn more about InsightIDR


    After you''ve got the basics down, you can use this API guide to find examples of requests and responses.'
servers:
- url: https://{region}.api.insight.rapid7.com/
  variables:
    region:
      default: us
      description: Insight API region
security: []
tags:
- name: Users
  description: An API used to find and search InsightIDR users. See https://docs.rapid7.com/insightidr/users-and-accounts-on-your-domain for further information on users.
paths:
  /idr/v1/users/_search:
    post:
      tags:
      - Users
      summary: Search users
      description: 'A search API for users. You can search for users matching the given search criteria.


        FieldCan Search?Can Sort?Type


        first_nameYesYesString


        last_nameYesYesString


        nameYesYesString


        domainYesNoString'
      operationId: searchUsers
      parameters:
      - name: index
        in: query
        description: The optional, 0 based index of the page to retrieve. Must be an integer greater than or equal to 0.
        required: false
        schema:
          minimum: 0
          type: integer
          default: 0
        example: 0
      - name: size
        in: query
        description: The optional size of the page to retrieve. Must be an integer greater than 0 or less than or equal to 1000.
        required: false
        schema:
          maximum: 1000
          minimum: 1
          type: integer
          default: 20
        example: 20
      requestBody:
        description: The criteria and sorting information for searching.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageUserV2'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Insufficient Permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Entity Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '405':
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '502':
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /idr/v1/users/{rrn}:
    get:
      tags:
      - Users
      summary: Get user by RRN
      description: Retrieve a user with the given RRN (Rapid7 Resource Name).
      operationId: getUserByRrn
      parameters:
      - name: rrn
        in: path
        description: The RRN of the user.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserV2'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Insufficient Permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Entity Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '405':
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '502':
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    PageMetadata:
      required:
      - index
      - size
      - total_data
      - total_pages
      type: object
      properties:
        index:
          type: integer
          description: 'The 0 based index of the page retrieved. '
          format: int32
          example: 0
        size:
          type: integer
          description: 'The size of the page requested. '
          format: int32
          example: 20
        total_pages:
          type: integer
          description: 'The total number of pages available with the given filter parameters. '
          format: int32
          example: 1
        total_data:
          type: integer
          description: 'The total number of results available with the given filter parameters. '
          format: int64
          example: 15
      description: The pagination parameters used to generate this page result. Depending on the API, additional parameters may be dynamically present.
    SearchRequestSort:
      type: object
      properties:
        field:
          type: string
          description: The field to sort by.
          example: name
        order:
          type: string
          description: The sorting direction. Sorting is case-insensitive when sorting strings.
          enum:
          - ASC
          - DESC
          - ASC,DESC
      description: The sorting information.
    UserV2:
      required:
      - domain
      - name
      - rrn
      type: object
      properties:
        rrn:
          type: string
          description: The unique identifier for this user.
          example: rrn:uba:us:6bcf6c5b-552d-49a4-a3f5-259e0514585f:user:83002c85d7c6
        first_name:
          type: string
          description: The first name of this user, if known.
          example: John
        last_name:
          type: string
          description: The last name of this user, if known.
          example: Doe
        name:
          type: string
          description: The name of this user.
          example: John Doe
        domain:
          type: string
          description: The domain this user is associated with.
          example: tor.acme.com
      description: The list of data that matches the pagination parameters. If no results match this will be an empty list.
    SearchRequestCriteria:
      type: object
      properties:
        field:
          type: string
          description: The field to search within.
          example: name
        operator:
          type: string
          description: The search operation to perform. All operators are case-insensitive when operating on strings.
          enum:
          - EQUALS
          - CONTAINS
          - IN
        value:
          type: object
          description: The value to search for.
      description: The criteria for which entities to return.
    PageUserV2:
      required:
      - data
      - metadata
      type: object
      properties:
        data:
          type: array
          description: The list of data that matches the pagination parameters. If no results match this will be an empty list.
          items:
            $ref: '#/components/schemas/UserV2'
        metadata:
          $ref: '#/components/schemas/PageMetadata'
    SearchRequest:
      type: object
      properties:
        search:
          type: array
          description: The criteria for which entities to return.
          items:
            $ref: '#/components/schemas/SearchRequestCriteria'
        sort:
          type: array
          description: The sorting information.
          items:
            $ref: '#/components/schemas/SearchRequestSort'
    ErrorResponse:
      required:
      - message
      type: object
      properties:
        message:
          type: string
          description: A human-readable message describing the error that occurred.
          example: A human-readable message describing the error that occurred.
        correlation_id:
          type: string
          description: An identifier that uniquely identifies the failed request.
          example: 6b6503c8-2da9-41c0-94cb-2f34069e00cd
externalDocs:
  description: Product docs
  url: https://insightidr.help.rapid7.com/docs
