openapi: 3.2.0
info:
  title: InsightIDR Collectors API
  version: v1
  description: 'Introduction


    Welcome to the reference documentation for the InsightIDR public APIs.


    Here are a few resources to help you learn how to start using our APIs:


    Learn about basic concepts and capabilities


    Get an Insight platform API key to set up authentication


    See available Insight product APIs


    Learn more about InsightIDR


    After you''ve got the basics down, you can use this API guide to find examples of requests and responses.'
servers:
- url: https://{region}.api.insight.rapid7.com/
  variables:
    region:
      default: us
      description: Insight API region
security: []
tags:
- name: Collectors
  description: An API used to manage collectors for an organization.
paths:
  /idr/v1/collectors:
    post:
      tags:
      - Collectors
      summary: Add Collector
      description: Add a new collector. The API key used must be associated with a user with the collection administration role.
      operationId: addCollector
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddCollectorRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddCollectorResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Insufficient Permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Entity Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '405':
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '502':
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '504':
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    RRN1:
      type: object
      properties:
        partition:
          type: string
        service:
          type: string
        regionCode:
          type: string
        organizationId:
          type: string
        resourceTypes:
          type: array
          items:
            type: string
        resource:
          type: string
      description: The unique identifier for this collector.
      example: rrn:collection:us:6bcf6c5b-552d-49a4-a3f5-259e0514585f:collector:ae1d4845-8ce8-4072-b4d5-77171387fb6a
    ErrorResponse:
      required:
      - message
      type: object
      properties:
        message:
          type: string
          description: A human-readable message describing the error that occurred.
          example: A human-readable message describing the error that occurred.
        correlation_id:
          type: string
          description: An identifier that uniquely identifies the failed request.
          example: 6b6503c8-2da9-41c0-94cb-2f34069e00cd
    AddCollectorResponse:
      required:
      - id
      - name
      - rrn
      type: object
      properties:
        id:
          type: string
          description: The identifier for this collector.
          example: ae1d4845-8ce8-4072-b4d5-77171387fb6a
        rrn:
          $ref: '#/components/schemas/RRN1'
        name:
          type: string
          description: The name of this collector.
          example: My Collector
      description: Response from creating a collector
    AddCollectorRequest:
      required:
      - key
      - name
      type: object
      properties:
        name:
          type: string
          description: The name for the new collector. Must be unique.
          example: My Collector
        key:
          type: string
          description: The registration key for the collector. Must be unique, and a valid UUID.
          example: ae1d4845-8ce8-4072-b4d5-77171387fb6a
        deployment_type:
          type: string
          description: Optional indication of how the collector is deployed.
          example: kubernetes
      description: Request body for creating a collector
externalDocs:
  description: Product docs
  url: https://insightidr.help.rapid7.com/docs
